# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CommonFramework' do
    pod 'FMDB'
    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'SDWebImage', '~>3.7'
    pod 'DateTools'
    pod 'Mantle'
    pod 'MTLFMDBAdapter'
end
